import { Location } from '../types';

const T = [
  'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?q=80&w=2070',
  'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=2070',
  'https://images.unsplash.com/photo-1528360983277-13d401cdc186?q=80&w=2070',
  'https://images.unsplash.com/photo-1542931287-023b922fa89b?q=80&w=2070',
  'https://images.unsplash.com/photo-1506197603440-664426514781?q=80&w=2070',
  'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?q=80&w=2070',
  'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?q=80&w=2070',
];

export const LOCATIONS: Location[] = [
  // =============================================
  // KYOTO (k1–k100)
  // =============================================

  // --- Kyoto: Culture ---
  { id: 'k1', name: 'Kiyomizu-dera', kanji: '清水寺', category: 'Culture', area: 'Kyoto', priority: 1, coordinates: { lat: 34.9949, lng: 135.7850 }, shortDescription: 'UNESCO temple famous for its wooden stage with stunning city views.', imageUrl: T[2], tags: ['temple', 'unesco', 'higashiyama'] },
  { id: 'k2', name: 'Yasaka Pagoda', kanji: '法観寺', category: 'Culture', area: 'Kyoto', priority: 1, coordinates: { lat: 34.9986, lng: 135.7794 }, shortDescription: 'Iconic five-story pagoda in the Higashiyama district.', imageUrl: T[1], tags: ['pagoda', 'higashiyama', 'photo-spot'] },
  { id: 'k9', name: 'Fushimi Inari', kanji: '伏見稲荷大社', category: 'Culture', area: 'Kyoto', priority: 1, coordinates: { lat: 34.9671, lng: 135.7727 }, shortDescription: 'Thousands of vermillion torii gates climbing the mountain.', imageUrl: T[5], tags: ['shrine', 'torii', 'hiking', 'fox'] },
  { id: 'k10', name: 'Kinkaku-ji', kanji: '金閣寺', category: 'Culture', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0394, lng: 135.7292 }, shortDescription: 'The Golden Pavilion reflected in a mirror pond.', imageUrl: T[0], tags: ['temple', 'gold', 'unesco', 'garden'] },
  { id: 'k17', name: 'Kamigamo Shrine', kanji: '上賀茂神社', category: 'Culture', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0597, lng: 135.7527 }, shortDescription: 'One of Kyoto\'s oldest shrines, UNESCO heritage.', imageUrl: T[5], tags: ['shrine', 'unesco', 'shinto', 'festival'] },
  { id: 'k18', name: 'Shimogamo Shrine', kanji: '下鴨神社', category: 'Culture', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0385, lng: 135.7723 }, shortDescription: 'Ancient forest shrine sacred to Kyoto since pre-history.', imageUrl: T[5], tags: ['shrine', 'forest', 'festival', 'aoi-matsuri'] },
  { id: 'k19', name: 'Heian Shrine', kanji: '平安神宮', category: 'Culture', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0160, lng: 135.7824 }, shortDescription: 'Grand shrine with massive torii gate and beautiful garden.', imageUrl: T[5], tags: ['shrine', 'garden', 'cherry-blossom', 'torii'] },
  { id: 'k20', name: 'Kitano Tenmangu', kanji: '北野天満宮', category: 'Culture', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0313, lng: 135.7352 }, shortDescription: 'Shrine of the god of learning, famous for plum blossoms.', imageUrl: T[5], tags: ['shrine', 'plum-blossom', 'festival', 'tenjin'] },
  { id: 'k21', name: 'Yasaka Shrine', kanji: '八坂神社', category: 'Culture', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0036, lng: 135.7786 }, shortDescription: 'Guardian shrine of Gion, home of the Gion Festival.', imageUrl: T[5], tags: ['shrine', 'gion', 'festival', 'matsuri'] },
  { id: 'k22', name: 'Sanjusangendo', kanji: '三十三間堂', category: 'Culture', area: 'Kyoto', priority: 1, coordinates: { lat: 34.9876, lng: 135.7717 }, shortDescription: 'Hall with 1001 standing statues of Kannon.', imageUrl: T[2], tags: ['temple', 'buddha', 'sculpture', 'national-treasure'] },
  { id: 'k23', name: 'Ninna-ji', kanji: '仁和寺', category: 'Culture', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0312, lng: 135.7130 }, shortDescription: 'Imperial temple with late-blooming cherry trees.', imageUrl: T[2], tags: ['temple', 'cherry-blossom', 'unesco', 'imperial'] },
  { id: 'k24', name: 'Daitoku-ji', kanji: '大徳寺', category: 'Culture', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0437, lng: 135.7453 }, shortDescription: 'Major Rinzai Zen complex with tea ceremony heritage.', imageUrl: T[2], tags: ['temple', 'zen', 'tea-ceremony', 'garden'] },

  // --- Kyoto: Zen ---
  { id: 'k3', name: 'Kodai-ji', kanji: '高台寺', category: 'Zen', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0000, lng: 135.7811 }, shortDescription: 'Beautiful Zen temple built for Lady Nene.', imageUrl: T[6], tags: ['meditation', 'garden', 'tea', 'toyotomi'] },
  { id: 'k4', name: 'Kennin-ji', kanji: '建仁寺', category: 'Zen', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0011, lng: 135.7735 }, shortDescription: 'The oldest Zen temple in Kyoto, home to the Twin Dragons ceiling.', imageUrl: T[6], tags: ['meditation', 'dragon', 'zen', 'calligraphy'] },
  { id: 'k7', name: 'Tenryu-ji', kanji: '天龍寺', category: 'Zen', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0158, lng: 135.6737 }, shortDescription: 'World Heritage Zen temple with stunning garden in Arashiyama.', imageUrl: T[6], tags: ['meditation', 'garden', 'unesco', 'arashiyama'] },
  { id: 'k11', name: 'Ryoan-ji', kanji: '龍安寺', category: 'Zen', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0345, lng: 135.7185 }, shortDescription: 'Home to Japan\'s most famous rock garden.', imageUrl: T[6], tags: ['rock-garden', 'meditation', 'zen', 'minimalism'] },
  { id: 'k14', name: 'Ginkaku-ji', kanji: '銀閣寺', category: 'Zen', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0268, lng: 135.7982 }, shortDescription: 'The Silver Pavilion, a masterpiece of wabi-sabi aesthetics.', imageUrl: T[0], tags: ['wabi-sabi', 'garden', 'meditation', 'moss'] },
  { id: 'k15', name: 'Tofuku-ji', kanji: '東福寺', category: 'Zen', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9762, lng: 135.7740 }, shortDescription: 'Stunning autumn foliage and Zen gardens.', imageUrl: T[0], tags: ['autumn-leaves', 'garden', 'bridge', 'meditation'] },
  { id: 'k25', name: 'Nanzen-ji', kanji: '南禅寺', category: 'Zen', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0112, lng: 135.7926 }, shortDescription: 'Head temple of Nanzen-ji Rinzai school with aqueduct ruins.', imageUrl: T[6], tags: ['meditation', 'garden', 'aqueduct', 'zen'] },
  { id: 'k26', name: 'Shisen-do', kanji: '詩仙堂', category: 'Zen', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0446, lng: 135.7970 }, shortDescription: 'Poet\'s retreat with serene garden and deer-scarer fountain.', imageUrl: T[6], tags: ['garden', 'meditation', 'poetry', 'moss'] },
  { id: 'k27', name: 'Eikan-do', kanji: '永観堂', category: 'Zen', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0152, lng: 135.7935 }, shortDescription: 'Temple renowned for spectacular autumn illuminations.', imageUrl: T[0], tags: ['autumn-leaves', 'illumination', 'garden', 'meditation'] },
  { id: 'k28', name: 'Myoshin-ji', kanji: '妙心寺', category: 'Zen', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0248, lng: 135.7196 }, shortDescription: 'Largest Rinzai Zen complex with 46 sub-temples.', imageUrl: T[6], tags: ['zen', 'meditation', 'garden', 'dragon'] },
  { id: 'k29', name: 'Saihō-ji (Moss Temple)', kanji: '西芳寺', category: 'Zen', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9917, lng: 135.6836 }, shortDescription: 'UNESCO temple with 120 varieties of moss covering the garden.', imageUrl: T[6], tags: ['moss', 'meditation', 'unesco', 'garden'] },

  // --- Kyoto: Samurai ---
  { id: 'k16', name: 'Nijo Castle', kanji: '二条城', category: 'Samurai', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0142, lng: 135.7480 }, shortDescription: 'Tokugawa shogunate castle with nightingale floors.', imageUrl: T[2], tags: ['castle', 'tokugawa', 'nightingale', 'bushido'] },
  { id: 'k30', name: 'Fushimi Castle Ruins', kanji: '伏見桃山城', category: 'Samurai', area: 'Kyoto', priority: 3, coordinates: { lat: 34.9395, lng: 135.7882 }, shortDescription: 'Reconstructed castle on Toyotomi Hideyoshi\'s historic site.', imageUrl: T[2], tags: ['castle', 'toyotomi', 'history', 'park'] },
  { id: 'k31', name: 'Kyoto Samurai & Ninja Museum', kanji: '京都侍忍者ミュージアム', category: 'Samurai', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0037, lng: 135.7619 }, shortDescription: 'Hands-on museum with real samurai armor and sword demonstrations.', imageUrl: T[2], tags: ['sword', 'armor', 'ninja', 'museum', 'experience'] },
  { id: 'k32', name: 'Mibu-dera', kanji: '壬生寺', category: 'Samurai', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0042, lng: 135.7411 }, shortDescription: 'Temple connected to the Shinsengumi samurai group.', imageUrl: T[2], tags: ['shinsengumi', 'bushido', 'history', 'temple'] },
  { id: 'k33', name: 'Shinsengumi HQ (Yagi House)', kanji: '八木邸', category: 'Samurai', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0040, lng: 135.7403 }, shortDescription: 'Former headquarters of the Shinsengumi samurai police.', imageUrl: T[2], tags: ['shinsengumi', 'bushido', 'history', 'bakumatsu'] },
  { id: 'k34', name: 'Nijo Jinya', kanji: '二条陣屋', category: 'Samurai', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0120, lng: 135.7505 }, shortDescription: 'Merchant house with hidden rooms and samurai-era traps.', imageUrl: T[2], tags: ['ninja', 'hidden-rooms', 'tokugawa', 'architecture'] },
  { id: 'k35', name: 'Ryozen Museum of History', kanji: '霊山歴史館', category: 'Samurai', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9996, lng: 135.7823 }, shortDescription: 'Museum dedicated to the Bakumatsu era and Meiji Restoration.', imageUrl: T[2], tags: ['bakumatsu', 'history', 'sword', 'museum'] },
  { id: 'k36', name: 'Teradaya Inn', kanji: '寺田屋', category: 'Samurai', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9307, lng: 135.7612 }, shortDescription: 'Historic inn where Sakamoto Ryoma survived an assassination.', imageUrl: T[2], tags: ['bakumatsu', 'ryoma', 'history', 'fushimi'] },

  // --- Kyoto: Food ---
  { id: 'k6', name: 'Pontocho Alley', kanji: '先斗町', category: 'Food', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0053, lng: 135.7710 }, shortDescription: 'Atmospheric narrow alley lined with restaurants and bars.', imageUrl: T[3], tags: ['kaiseki', 'sake', 'dining', 'nightlife'] },
  { id: 'k12', name: 'Nishiki Market', kanji: '錦市場', category: 'Food', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0050, lng: 135.7649 }, shortDescription: 'Kyoto\'s kitchen - a 400-year-old food market.', imageUrl: T[3], tags: ['market', 'street-food', 'pickles', 'matcha'] },
  { id: 'k37', name: 'Gion Kappa Restaurant District', kanji: '祇園縄手通', category: 'Food', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0040, lng: 135.7750 }, shortDescription: 'Traditional Kyoto-style restaurants along the Shirakawa canal.', imageUrl: T[3], tags: ['kaiseki', 'tofu', 'yudofu', 'traditional'] },
  { id: 'k38', name: 'Fushimi Sake District', kanji: '伏見酒蔵', category: 'Food', area: 'Kyoto', priority: 1, coordinates: { lat: 34.9335, lng: 135.7580 }, shortDescription: 'Historic sake brewery district with tastings and tours.', imageUrl: T[3], tags: ['sake', 'brewery', 'tasting', 'fushimi'] },
  { id: 'k39', name: 'Ichiran Ramen Kyoto', kanji: '一蘭 京都河原町店', category: 'Food', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0042, lng: 135.7688 }, shortDescription: 'Famous tonkotsu ramen chain with private booth seating.', imageUrl: T[3], tags: ['ramen', 'tonkotsu', 'late-night'] },
  { id: 'k40', name: 'Kyoto Ramen Koji', kanji: '京都拉麺小路', category: 'Food', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9853, lng: 135.7587 }, shortDescription: 'Ramen theme floor in Kyoto Station with 9 shops from across Japan.', imageUrl: T[3], tags: ['ramen', 'variety', 'station'] },
  { id: 'k41', name: 'Tsuruya Yoshinobu', kanji: '鶴屋吉信', category: 'Food', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0282, lng: 135.7534 }, shortDescription: 'Historic wagashi confectionery making traditional sweets since 1803.', imageUrl: T[3], tags: ['wagashi', 'matcha', 'sweets', 'traditional'] },
  { id: 'k42', name: 'Ippodo Tea House', kanji: '一保堂茶舗', category: 'Food', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0118, lng: 135.7673 }, shortDescription: 'Premier tea house selling Uji matcha since 1717.', imageUrl: T[3], tags: ['matcha', 'tea', 'uji', 'traditional'] },
  { id: 'k43', name: 'Gion Tsujiri', kanji: '祇園辻利', category: 'Food', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0036, lng: 135.7750 }, shortDescription: 'Famous matcha sweets and parfaits in Gion.', imageUrl: T[3], tags: ['matcha', 'sweets', 'parfait', 'gion'] },
  { id: 'k44', name: 'Arashiyama Togetsu-kyo Area Dining', kanji: '嵐山渡月橋', category: 'Food', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0105, lng: 135.6778 }, shortDescription: 'Scenic riverside dining area with tofu and soba specialties.', imageUrl: T[3], tags: ['tofu', 'soba', 'arashiyama', 'riverside'] },

  // --- Kyoto: Nature ---
  { id: 'k8', name: 'Bamboo Forest', kanji: '竹林の小径', category: 'Nature', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0169, lng: 135.6720 }, shortDescription: 'Otherworldly path through towering bamboo groves.', imageUrl: T[4], tags: ['bamboo', 'arashiyama', 'hiking', 'photo-spot'] },
  { id: 'k13', name: 'Philosopher\'s Path', kanji: '哲学の道', category: 'Nature', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0230, lng: 135.7940 }, shortDescription: 'Peaceful canal-side walk between temples.', imageUrl: T[6], tags: ['cherry-blossom', 'walk', 'canal', 'autumn-leaves'] },
  { id: 'k45', name: 'Mount Kurama', kanji: '鞍馬山', category: 'Nature', area: 'Kyoto', priority: 2, coordinates: { lat: 35.1152, lng: 135.7688 }, shortDescription: 'Sacred mountain with hiking trail and tengu legends.', imageUrl: T[4], tags: ['mountain', 'hiking', 'tengu', 'spiritual'] },
  { id: 'k46', name: 'Kibune', kanji: '貴船', category: 'Nature', area: 'Kyoto', priority: 2, coordinates: { lat: 35.1207, lng: 135.7628 }, shortDescription: 'Mountain village with kawadoko river dining in summer.', imageUrl: T[4], tags: ['river', 'mountain', 'kawadoko', 'summer'] },
  { id: 'k47', name: 'Kamogawa River Delta', kanji: '鴨川デルタ', category: 'Nature', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0297, lng: 135.7706 }, shortDescription: 'Scenic river convergence popular with locals for relaxation.', imageUrl: T[4], tags: ['river', 'local', 'relaxation', 'cherry-blossom'] },
  { id: 'k48', name: 'Maruyama Park', kanji: '円山公園', category: 'Nature', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0027, lng: 135.7812 }, shortDescription: 'Kyoto\'s most famous cherry blossom viewing spot.', imageUrl: T[4], tags: ['cherry-blossom', 'park', 'hanami', 'garden'] },
  { id: 'k49', name: 'Tadasu no Mori', kanji: '糺の森', category: 'Nature', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0370, lng: 135.7720 }, shortDescription: 'Primeval forest within Shimogamo Shrine grounds.', imageUrl: T[4], tags: ['forest', 'ancient', 'spiritual', 'walk'] },
  { id: 'k50', name: 'Ohara Countryside', kanji: '大原', category: 'Nature', area: 'Kyoto', priority: 3, coordinates: { lat: 35.1182, lng: 135.8350 }, shortDescription: 'Rural valley with terraced fields and temple gardens.', imageUrl: T[4], tags: ['countryside', 'autumn-leaves', 'temple', 'mountain'] },
  { id: 'k51', name: 'Takao Gorge', kanji: '高雄', category: 'Nature', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0548, lng: 135.6667 }, shortDescription: 'Mountain gorge famous for autumn colors and ancient temples.', imageUrl: T[4], tags: ['gorge', 'autumn-leaves', 'hiking', 'river'] },

  // --- Kyoto: DailyLife ---
  { id: 'k5', name: 'Gion Tatsumi Bridge', kanji: '辰巳大明神', category: 'DailyLife', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0055, lng: 135.7738 }, shortDescription: 'The heart of Gion geisha district.', imageUrl: T[3], tags: ['geisha', 'neighborhood', 'gion', 'traditional'] },
  { id: 'k52', name: 'Ninen-zaka & Sannen-zaka', kanji: '二年坂・三年坂', category: 'DailyLife', area: 'Kyoto', priority: 1, coordinates: { lat: 34.9968, lng: 135.7800 }, shortDescription: 'Preserved stone-paved slopes lined with traditional shops.', imageUrl: T[1], tags: ['neighborhood', 'traditional', 'shopping', 'walk'] },
  { id: 'k53', name: 'Toji Flea Market', kanji: '東寺弘法市', category: 'DailyLife', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9806, lng: 135.7477 }, shortDescription: 'Monthly flea market at Toji Temple on the 21st.', imageUrl: T[3], tags: ['market', 'flea-market', 'local', 'antique'] },
  { id: 'k54', name: 'Kyoto Station', kanji: '京都駅', category: 'DailyLife', area: 'Kyoto', priority: 1, coordinates: { lat: 34.9855, lng: 135.7588 }, shortDescription: 'Modern architectural marvel serving as Kyoto\'s transport hub.', imageUrl: T[2], tags: ['architecture', 'modern', 'station', 'hub'] },
  { id: 'k55', name: 'Demachi Masugata Shotengai', kanji: '出町桝形商店街', category: 'DailyLife', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0312, lng: 135.7678 }, shortDescription: 'Beloved local shopping arcade with old-fashioned atmosphere.', imageUrl: T[3], tags: ['market', 'local', 'neighborhood', 'shotengai'] },
  { id: 'k56', name: 'Funaoka Onsen', kanji: '船岡温泉', category: 'DailyLife', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0385, lng: 135.7420 }, shortDescription: 'Historic public bath with beautiful tile work from the 1920s.', imageUrl: T[2], tags: ['onsen', 'bath', 'local', 'retro'] },
  { id: 'k57', name: 'Kyoto Imperial Palace', kanji: '京都御所', category: 'DailyLife', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0244, lng: 135.7621 }, shortDescription: 'Former imperial residence with vast park grounds open to public.', imageUrl: T[0], tags: ['imperial', 'park', 'history', 'garden'] },

  // --- Kyoto: Craft ---
  { id: 'k58', name: 'Kiyomizu-yaki Pottery District', kanji: '清水焼の郷', category: 'Craft', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9798, lng: 135.7888 }, shortDescription: 'Pottery district producing Kyoto\'s famous Kiyomizu-yaki ceramics.', imageUrl: T[3], tags: ['pottery', 'ceramics', 'workshop', 'kiyomizu'] },
  { id: 'k59', name: 'Nishijin Textile Center', kanji: '西陣織会館', category: 'Craft', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0320, lng: 135.7435 }, shortDescription: 'Center showcasing Kyoto\'s famous Nishijin silk weaving tradition.', imageUrl: T[3], tags: ['textile', 'silk', 'kimono', 'weaving'] },
  { id: 'k60', name: 'Kyoto Museum of Crafts and Design', kanji: '京都伝統産業ミュージアム', category: 'Craft', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0160, lng: 135.7830 }, shortDescription: 'Museum showcasing 74 categories of Kyoto traditional crafts.', imageUrl: T[3], tags: ['museum', 'lacquerware', 'textile', 'pottery'] },
  { id: 'k61', name: 'Kaikado Tea Canister Shop', kanji: '開化堂', category: 'Craft', area: 'Kyoto', priority: 3, coordinates: { lat: 34.9913, lng: 135.7616 }, shortDescription: 'Hand-made tea canisters crafted since 1875.', imageUrl: T[3], tags: ['metalwork', 'tea', 'traditional', 'artisan'] },
  { id: 'k62', name: 'Kyoto Yuzen Dyeing Workshop', kanji: '京友禅体験工房', category: 'Craft', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0082, lng: 135.7545 }, shortDescription: 'Hands-on experience of Kyoto\'s famous Yuzen dyeing technique.', imageUrl: T[3], tags: ['dyeing', 'yuzen', 'textile', 'experience'] },
  { id: 'k63', name: 'Sfera Building (Craft Select Shop)', kanji: 'スフェラビル', category: 'Craft', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0043, lng: 135.7730 }, shortDescription: 'Contemporary craft gallery blending traditional and modern design.', imageUrl: T[3], tags: ['contemporary', 'design', 'gallery', 'artisan'] },
  { id: 'k64', name: 'Kamigyo Paper Workshop', kanji: '楽紙舘', category: 'Craft', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0280, lng: 135.7505 }, shortDescription: 'Traditional washi paper making experience in machiya house.', imageUrl: T[3], tags: ['paper', 'washi', 'workshop', 'traditional'] },
  { id: 'k65', name: 'Asahi Pottery Workshop', kanji: '朝日焼窯元', category: 'Craft', area: 'Kyoto', priority: 3, coordinates: { lat: 34.8890, lng: 135.8120 }, shortDescription: 'Over 400-year-old Uji pottery kiln open for workshop visits.', imageUrl: T[3], tags: ['pottery', 'uji', 'workshop', 'tea'] },

  // --- Kyoto: Anime ---
  { id: 'k66', name: 'Kyoto International Manga Museum', kanji: '京都国際マンガミュージアム', category: 'Anime', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0122, lng: 135.7590 }, shortDescription: 'Museum with 300,000+ manga volumes in a former school building.', imageUrl: T[1], tags: ['manga', 'museum', 'library', 'otaku'] },
  { id: 'k67', name: 'Toei Kyoto Studio Park', kanji: '東映太秦映画村', category: 'Anime', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0158, lng: 135.7084 }, shortDescription: 'Film studio theme park with anime events and cosplay.', imageUrl: T[1], tags: ['cosplay', 'naruto', 'anime-events', 'film'] },
  { id: 'k68', name: 'Sembon Torii (Fushimi Inari)', kanji: '千本鳥居', category: 'Anime', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9677, lng: 135.7728 }, shortDescription: 'Iconic torii tunnel featured in countless anime scenes.', imageUrl: T[5], tags: ['anime-location', 'naruto', 'inari', 'photo-spot'] },
  { id: 'k69', name: 'Animate Kyoto', kanji: 'アニメイト京都', category: 'Anime', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0042, lng: 135.7630 }, shortDescription: 'Major anime goods store in central Kyoto.', imageUrl: T[1], tags: ['otaku', 'goods', 'manga', 'shopping'] },
  { id: 'k70', name: 'Kyoto Animation Studio Area', kanji: '京都アニメーション周辺', category: 'Anime', area: 'Kyoto', priority: 3, coordinates: { lat: 34.9160, lng: 135.7933 }, shortDescription: 'Area near the legendary anime studio behind K-On! and Violet Evergarden.', imageUrl: T[1], tags: ['k-on', 'violet-evergarden', 'studio', 'pilgrimage'] },
  { id: 'k71', name: 'Teramachi Manga Street', kanji: '寺町通マンガストリート', category: 'Anime', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0080, lng: 135.7658 }, shortDescription: 'Covered arcade with multiple manga and anime shops.', imageUrl: T[1], tags: ['manga', 'shopping', 'otaku', 'arcade'] },

  // --- Kyoto: Shopping ---
  { id: 'k72', name: 'Shinkyogoku Shopping Street', kanji: '新京極商店街', category: 'Shopping', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0058, lng: 135.7665 }, shortDescription: 'Kyoto\'s oldest shopping arcade with souvenirs and fashion.', imageUrl: T[3], tags: ['souvenir', 'arcade', 'fashion', 'traditional'] },
  { id: 'k73', name: 'Teramachi Street', kanji: '寺町通', category: 'Shopping', area: 'Kyoto', priority: 1, coordinates: { lat: 35.0070, lng: 135.7658 }, shortDescription: 'Historic shopping street with antiques, books and tea shops.', imageUrl: T[3], tags: ['antique', 'books', 'tea', 'traditional'] },
  { id: 'k74', name: 'Isetan Kyoto', kanji: 'ジェイアール京都伊勢丹', category: 'Shopping', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9861, lng: 135.7581 }, shortDescription: 'Premium department store inside Kyoto Station building.', imageUrl: T[3], tags: ['department-store', 'luxury', 'fashion', 'food'] },
  { id: 'k75', name: 'Kitayama Street', kanji: '北山通', category: 'Shopping', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0500, lng: 135.7580 }, shortDescription: 'Trendy street with boutiques, cafes, and botanical garden.', imageUrl: T[3], tags: ['boutique', 'cafe', 'local-brand', 'modern'] },
  { id: 'k76', name: 'Arashiyama Bamboo Street Shops', kanji: '嵐山竹林参道', category: 'Shopping', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0142, lng: 135.6748 }, shortDescription: 'Charming shops selling bamboo crafts and Kyoto souvenirs.', imageUrl: T[3], tags: ['souvenir', 'bamboo', 'crafts', 'arashiyama'] },
  { id: 'k77', name: 'Kobo-san Flea Market (Toji)', kanji: '弘法市', category: 'Shopping', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9806, lng: 135.7477 }, shortDescription: 'Huge monthly antique market with 1200+ vendors.', imageUrl: T[3], tags: ['antique', 'flea-market', 'vintage', 'local'] },
  { id: 'k78', name: 'Kyoto Handicraft Center', kanji: '京都ハンディクラフトセンター', category: 'Shopping', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0170, lng: 135.7835 }, shortDescription: 'One-stop shop for all Kyoto traditional crafts and experiences.', imageUrl: T[3], tags: ['souvenir', 'crafts', 'experience', 'traditional'] },

  // =============================================
  // OSAKA (o1–o100)
  // =============================================

  // --- Osaka: Food ---
  { id: 'o1', name: 'Dotonbori', kanji: '道頓堀', category: 'Food', area: 'Osaka', priority: 1, coordinates: { lat: 34.6687, lng: 135.5013 }, shortDescription: 'Osaka\'s iconic neon-lit food and entertainment district.', imageUrl: T[3], tags: ['street-food', 'takoyaki', 'okonomiyaki', 'nightlife'] },
  { id: 'o4', name: 'Shinsekai', kanji: '新世界', category: 'Food', area: 'Osaka', priority: 1, coordinates: { lat: 34.6525, lng: 135.5063 }, shortDescription: 'Retro neighborhood known for kushikatsu and Tsutenkaku Tower.', imageUrl: T[3], tags: ['kushikatsu', 'retro', 'tower', 'street-food'] },
  { id: 'o5', name: 'Kuromon Market', kanji: '黒門市場', category: 'Food', area: 'Osaka', priority: 1, coordinates: { lat: 34.6665, lng: 135.5076 }, shortDescription: 'Osaka\'s kitchen - fresh seafood and street food paradise.', imageUrl: T[3], tags: ['sushi', 'seafood', 'market', 'street-food'] },
  { id: 'o8', name: 'Hozenji Yokocho', kanji: '法善寺横丁', category: 'Food', area: 'Osaka', priority: 2, coordinates: { lat: 34.6685, lng: 135.5035 }, shortDescription: 'Atmospheric cobblestone alley with upscale kappo restaurants.', imageUrl: T[3], tags: ['kaiseki', 'kappo', 'traditional', 'sake'] },
  { id: 'o9', name: 'Juso Area Ramen Row', kanji: '十三ラーメン街', category: 'Food', area: 'Osaka', priority: 3, coordinates: { lat: 34.7224, lng: 135.4843 }, shortDescription: 'Local ramen concentration with hidden gem shops.', imageUrl: T[3], tags: ['ramen', 'local', 'hidden-gem'] },
  { id: 'o10', name: 'Namba Grand Kagetsu', kanji: 'なんばグランド花月', category: 'Food', area: 'Osaka', priority: 2, coordinates: { lat: 34.6676, lng: 135.5040 }, shortDescription: 'Comedy theater area surrounded by food stalls and yoshimoto curry.', imageUrl: T[3], tags: ['street-food', 'comedy', 'local', 'curry'] },
  { id: 'o11', name: 'Tsuruhashi Korean Town', kanji: '鶴橋コリアンタウン', category: 'Food', area: 'Osaka', priority: 2, coordinates: { lat: 34.6651, lng: 135.5310 }, shortDescription: 'Japan\'s largest Koreatown with yakiniku and kimchi markets.', imageUrl: T[3], tags: ['yakiniku', 'korean', 'market', 'street-food'] },
  { id: 'o12', name: 'Temma Tenjin Area', kanji: '天満天神周辺', category: 'Food', area: 'Osaka', priority: 2, coordinates: { lat: 34.6950, lng: 135.5118 }, shortDescription: 'Dense izakaya district near Tenjinbashi with 100+ small bars.', imageUrl: T[3], tags: ['izakaya', 'sake', 'local', 'nightlife'] },
  { id: 'o13', name: 'Rikuro Ojisan Cheesecake', kanji: 'りくろーおじさんの店', category: 'Food', area: 'Osaka', priority: 2, coordinates: { lat: 34.6680, lng: 135.5010 }, shortDescription: 'Famous jiggly cheesecake shop with queues around the block.', imageUrl: T[3], tags: ['sweets', 'cheesecake', 'souvenir', 'popular'] },
  { id: 'o14', name: 'Ajinoya Okonomiyaki', kanji: '味乃家', category: 'Food', area: 'Osaka', priority: 2, coordinates: { lat: 34.6687, lng: 135.5020 }, shortDescription: 'Legendary okonomiyaki restaurant in business since 1965.', imageUrl: T[3], tags: ['okonomiyaki', 'traditional', 'iconic'] },
  { id: 'o15', name: 'Minami Senba Cafe Area', kanji: '南船場カフェエリア', category: 'Food', area: 'Osaka', priority: 3, coordinates: { lat: 34.6780, lng: 135.4990 }, shortDescription: 'Trendy cafe district with specialty coffee and brunch spots.', imageUrl: T[3], tags: ['cafe', 'coffee', 'brunch', 'modern'] },

  // --- Osaka: Culture ---
  { id: 'o2', name: 'Namba Yasaka', kanji: '難波八阪神社', category: 'Culture', area: 'Osaka', priority: 1, coordinates: { lat: 34.6612, lng: 135.4965 }, shortDescription: 'Shrine famous for its giant lion head stage.', imageUrl: T[5], tags: ['shrine', 'lion', 'photo-spot', 'unique'] },
  { id: 'o6', name: 'Shitennoji', kanji: '四天王寺', category: 'Culture', area: 'Osaka', priority: 2, coordinates: { lat: 34.6535, lng: 135.5165 }, shortDescription: 'One of Japan\'s oldest temples, founded 593 AD.', imageUrl: T[2], tags: ['temple', 'ancient', 'buddhism', 'history'] },
  { id: 'o7', name: 'Sumiyoshi Taisha', kanji: '住吉大社', category: 'Culture', area: 'Osaka', priority: 2, coordinates: { lat: 34.6125, lng: 135.4927 }, shortDescription: 'Ancient shrine with distinctive architectural style.', imageUrl: T[5], tags: ['shrine', 'shinto', 'bridge', 'new-year'] },
  { id: 'o16', name: 'Osaka Tenmangu', kanji: '大阪天満宮', category: 'Culture', area: 'Osaka', priority: 2, coordinates: { lat: 34.6939, lng: 135.5133 }, shortDescription: 'Historic shrine hosting Tenjin Matsuri, one of Japan\'s top 3 festivals.', imageUrl: T[5], tags: ['shrine', 'festival', 'matsuri', 'tenjin'] },
  { id: 'o17', name: 'Hozenji Temple', kanji: '法善寺', category: 'Culture', area: 'Osaka', priority: 2, coordinates: { lat: 34.6682, lng: 135.5038 }, shortDescription: 'Tiny moss-covered Fudo statue in the heart of Minami.', imageUrl: T[5], tags: ['temple', 'moss', 'prayer', 'minami'] },
  { id: 'o18', name: 'National Bunraku Theatre', kanji: '国立文楽劇場', category: 'Culture', area: 'Osaka', priority: 2, coordinates: { lat: 34.6655, lng: 135.5117 }, shortDescription: 'Home of traditional Japanese puppet theater, UNESCO heritage.', imageUrl: T[2], tags: ['bunraku', 'puppet', 'theater', 'unesco'] },
  { id: 'o19', name: 'Isshinji Temple', kanji: '一心寺', category: 'Culture', area: 'Osaka', priority: 3, coordinates: { lat: 34.6513, lng: 135.5105 }, shortDescription: 'Unique temple that creates Buddha statues from cremation ashes.', imageUrl: T[2], tags: ['temple', 'unique', 'buddhism', 'modern'] },
  { id: 'o20', name: 'Aizen-do Temple', kanji: '愛染堂', category: 'Culture', area: 'Osaka', priority: 3, coordinates: { lat: 34.6517, lng: 135.5160 }, shortDescription: 'Temple of love with the oldest multi-story pagoda in Osaka.', imageUrl: T[2], tags: ['temple', 'love', 'pagoda', 'prayer'] },

  // --- Osaka: Samurai ---
  { id: 'o3', name: 'Osaka Castle', kanji: '大坂城', category: 'Samurai', area: 'Osaka', priority: 1, coordinates: { lat: 34.6873, lng: 135.5262 }, shortDescription: 'Toyotomi Hideyoshi\'s legendary castle.', imageUrl: T[2], tags: ['castle', 'toyotomi', 'armor', 'history'] },
  { id: 'o21', name: 'Osaka Castle Goza Ship', kanji: '大阪城御座船', category: 'Samurai', area: 'Osaka', priority: 2, coordinates: { lat: 34.6850, lng: 135.5240 }, shortDescription: 'Gold-leaf boat cruise around the castle moat like a feudal lord.', imageUrl: T[2], tags: ['castle', 'boat', 'toyotomi', 'experience'] },
  { id: 'o22', name: 'Osaka Museum of History', kanji: '大阪歴史博物館', category: 'Samurai', area: 'Osaka', priority: 2, coordinates: { lat: 34.6826, lng: 135.5191 }, shortDescription: 'Museum spanning 1400 years with Osaka Castle views.', imageUrl: T[2], tags: ['museum', 'history', 'toyotomi', 'naniwa'] },
  { id: 'o23', name: 'Sanada-maru Site', kanji: '真田丸跡', category: 'Samurai', area: 'Osaka', priority: 3, coordinates: { lat: 34.6565, lng: 135.5262 }, shortDescription: 'Site of Sanada Yukimura\'s legendary last stand fortress.', imageUrl: T[2], tags: ['sanada', 'siege', 'history', 'bushido'] },
  { id: 'o24', name: 'Tamatsukuri Inari Shrine', kanji: '玉造稲荷神社', category: 'Samurai', area: 'Osaka', priority: 3, coordinates: { lat: 34.6720, lng: 135.5270 }, shortDescription: 'Shrine associated with Toyotomi clan and the siege of Osaka.', imageUrl: T[5], tags: ['toyotomi', 'shrine', 'history', 'castle'] },
  { id: 'o25', name: 'Kishiwada Castle', kanji: '岸和田城', category: 'Samurai', area: 'Osaka', priority: 3, coordinates: { lat: 34.4605, lng: 135.3716 }, shortDescription: 'Coastal castle hosting the famous Danjiri festival.', imageUrl: T[2], tags: ['castle', 'festival', 'danjiri', 'coastal'] },

  // --- Osaka: Zen ---
  { id: 'o26', name: 'Shitennoji Gokuraku-jodo Garden', kanji: '四天王寺極楽浄土の庭', category: 'Zen', area: 'Osaka', priority: 2, coordinates: { lat: 34.6535, lng: 135.5155 }, shortDescription: 'Serene Pure Land garden within Shitennoji Temple.', imageUrl: T[6], tags: ['garden', 'meditation', 'temple', 'paradise'] },
  { id: 'o27', name: 'Keitaku-en Garden', kanji: '慶沢園', category: 'Zen', area: 'Osaka', priority: 2, coordinates: { lat: 34.6491, lng: 135.5093 }, shortDescription: 'Meiji-era strolling garden designed by master Jihei Ogawa.', imageUrl: T[6], tags: ['garden', 'meditation', 'pond', 'traditional'] },
  { id: 'o28', name: 'Katsuoji Temple', kanji: '勝尾寺', category: 'Zen', area: 'Osaka', priority: 2, coordinates: { lat: 34.8594, lng: 135.4905 }, shortDescription: 'Mountain temple covered in daruma dolls for success prayers.', imageUrl: T[6], tags: ['temple', 'daruma', 'mountain', 'meditation'] },
  { id: 'o29', name: 'Namba Parks Sky Garden', kanji: 'なんばパークスガーデン', category: 'Zen', area: 'Osaka', priority: 3, coordinates: { lat: 34.6620, lng: 135.5003 }, shortDescription: 'Rooftop canyon garden in the city center for urban tranquility.', imageUrl: T[6], tags: ['garden', 'urban', 'rooftop', 'relaxation'] },
  { id: 'o30', name: 'Fujita Museum Garden', kanji: '藤田美術館庭園', category: 'Zen', area: 'Osaka', priority: 3, coordinates: { lat: 34.6948, lng: 135.5271 }, shortDescription: 'Art museum with traditional Japanese garden near the castle.', imageUrl: T[6], tags: ['garden', 'art', 'tea', 'meditation'] },

  // --- Osaka: Nature ---
  { id: 'o31', name: 'Osaka Castle Park', kanji: '大阪城公園', category: 'Nature', area: 'Osaka', priority: 1, coordinates: { lat: 34.6871, lng: 135.5256 }, shortDescription: 'Vast park surrounding the castle, famous for cherry blossoms and plums.', imageUrl: T[4], tags: ['cherry-blossom', 'park', 'plum-blossom', 'garden'] },
  { id: 'o32', name: 'Minoh Falls', kanji: '箕面大滝', category: 'Nature', area: 'Osaka', priority: 1, coordinates: { lat: 34.8514, lng: 135.4687 }, shortDescription: 'Stunning 33m waterfall in a forested valley north of Osaka.', imageUrl: T[4], tags: ['waterfall', 'hiking', 'autumn-leaves', 'mountain'] },
  { id: 'o33', name: 'Nakanoshima Rose Garden', kanji: '中之島バラ園', category: 'Nature', area: 'Osaka', priority: 2, coordinates: { lat: 34.6936, lng: 135.4916 }, shortDescription: 'Beautiful rose garden on a river island in central Osaka.', imageUrl: T[4], tags: ['garden', 'rose', 'river', 'urban'] },
  { id: 'o34', name: 'Expo \'70 Commemorative Park', kanji: '万博記念公園', category: 'Nature', area: 'Osaka', priority: 2, coordinates: { lat: 34.8098, lng: 135.5326 }, shortDescription: 'Vast park from 1970 World Expo with Tower of the Sun sculpture.', imageUrl: T[4], tags: ['park', 'cherry-blossom', 'museum', 'expo'] },
  { id: 'o35', name: 'Nagai Botanical Garden', kanji: '長居植物園', category: 'Nature', area: 'Osaka', priority: 3, coordinates: { lat: 34.6133, lng: 135.5175 }, shortDescription: 'Large botanical garden with seasonal flowers and lake.', imageUrl: T[4], tags: ['garden', 'botanical', 'flowers', 'lake'] },
  { id: 'o36', name: 'Mount Ikoma', kanji: '生駒山', category: 'Nature', area: 'Osaka', priority: 3, coordinates: { lat: 34.6787, lng: 135.6768 }, shortDescription: 'Mountain on the Osaka-Nara border with panoramic night views.', imageUrl: T[4], tags: ['mountain', 'night-view', 'hiking', 'amusement-park'] },

  // --- Osaka: DailyLife ---
  { id: 'o37', name: 'Tenjinbashisuji Shopping Street', kanji: '天神橋筋商店街', category: 'DailyLife', area: 'Osaka', priority: 1, coordinates: { lat: 34.6997, lng: 135.5126 }, shortDescription: 'Japan\'s longest shopping street at 2.6km with local shops.', imageUrl: T[3], tags: ['shotengai', 'local', 'market', 'neighborhood'] },
  { id: 'o38', name: 'Spa World', kanji: 'スパワールド', category: 'DailyLife', area: 'Osaka', priority: 2, coordinates: { lat: 34.6525, lng: 135.5048 }, shortDescription: 'Massive onsen theme park with baths from around the world.', imageUrl: T[3], tags: ['onsen', 'bath', 'spa', 'entertainment'] },
  { id: 'o39', name: 'Tsutenkaku Tower', kanji: '通天閣', category: 'DailyLife', area: 'Osaka', priority: 1, coordinates: { lat: 34.6525, lng: 135.5064 }, shortDescription: 'Retro tower symbol of Osaka\'s Shinsekai neighborhood since 1912.', imageUrl: T[2], tags: ['tower', 'retro', 'landmark', 'observation'] },
  { id: 'o40', name: 'Nakanoshima District', kanji: '中之島', category: 'DailyLife', area: 'Osaka', priority: 2, coordinates: { lat: 34.6930, lng: 135.4962 }, shortDescription: 'River island district with museums, riverside walks, and modern architecture.', imageUrl: T[2], tags: ['riverside', 'architecture', 'museum', 'modern'] },
  { id: 'o41', name: 'Umeda Sky Building', kanji: '梅田スカイビル', category: 'DailyLife', area: 'Osaka', priority: 1, coordinates: { lat: 34.7052, lng: 135.4903 }, shortDescription: 'Futuristic connected twin towers with floating garden observatory.', imageUrl: T[2], tags: ['architecture', 'observation', 'modern', 'night-view'] },
  { id: 'o42', name: 'Shinmachi & Horie Area', kanji: '新町・堀江エリア', category: 'DailyLife', area: 'Osaka', priority: 3, coordinates: { lat: 34.6730, lng: 135.4920 }, shortDescription: 'Trendy neighborhood with independent shops, cafes and galleries.', imageUrl: T[3], tags: ['neighborhood', 'cafe', 'trendy', 'local'] },

  // --- Osaka: Craft ---
  { id: 'o43', name: 'Sakai Knife Museum', kanji: '堺刃物ミュージアム', category: 'Craft', area: 'Osaka', priority: 2, coordinates: { lat: 34.5735, lng: 135.4833 }, shortDescription: 'Museum showcasing Sakai\'s 600-year knife-making tradition.', imageUrl: T[3], tags: ['knife', 'blade', 'metalwork', 'museum'] },
  { id: 'o44', name: 'Sakai Traditional Craft Museum', kanji: '堺市伝統産業会館', category: 'Craft', area: 'Osaka', priority: 3, coordinates: { lat: 34.5734, lng: 135.4830 }, shortDescription: 'Local crafts including incense, knives, and Sakai textiles.', imageUrl: T[3], tags: ['incense', 'knife', 'textile', 'workshop'] },
  { id: 'o45', name: 'Kamigata Ukiyoe Museum', kanji: '上方浮世絵館', category: 'Craft', area: 'Osaka', priority: 3, coordinates: { lat: 34.6684, lng: 135.5040 }, shortDescription: 'Rare museum dedicated to Osaka-style ukiyo-e woodblock prints.', imageUrl: T[3], tags: ['ukiyo-e', 'woodblock', 'art', 'museum'] },
  { id: 'o46', name: 'Suita Beer Museum', kanji: 'アサヒビール吹田工場', category: 'Craft', area: 'Osaka', priority: 3, coordinates: { lat: 34.7622, lng: 135.5184 }, shortDescription: 'Asahi beer factory tour with tasting at Japan\'s first beer brewery.', imageUrl: T[3], tags: ['beer', 'brewery', 'tasting', 'factory'] },
  { id: 'o47', name: 'Cup Noodles Museum Osaka', kanji: 'カップヌードルミュージアム大阪', category: 'Craft', area: 'Osaka', priority: 1, coordinates: { lat: 34.8097, lng: 135.5346 }, shortDescription: 'Create your own custom cup noodle and learn instant ramen history.', imageUrl: T[3], tags: ['ramen', 'museum', 'experience', 'factory'] },

  // --- Osaka: Anime ---
  { id: 'o48', name: 'Den Den Town', kanji: '日本橋でんでんタウン', category: 'Anime', area: 'Osaka', priority: 1, coordinates: { lat: 34.6598, lng: 135.5053 }, shortDescription: 'Osaka\'s Akihabara - electronics, manga and anime goods paradise.', imageUrl: T[1], tags: ['otaku', 'manga', 'figures', 'electronics'] },
  { id: 'o49', name: 'Animate Osaka Nipponbashi', kanji: 'アニメイト大阪日本橋', category: 'Anime', area: 'Osaka', priority: 2, coordinates: { lat: 34.6600, lng: 135.5057 }, shortDescription: 'Multi-floor anime goods store in the heart of otaku town.', imageUrl: T[1], tags: ['otaku', 'goods', 'manga', 'shopping'] },
  { id: 'o50', name: 'Mandarake Grand Chaos', kanji: 'まんだらけグランドカオス', category: 'Anime', area: 'Osaka', priority: 1, coordinates: { lat: 34.6592, lng: 135.5055 }, shortDescription: 'Massive second-hand manga, anime figures and rare collectibles shop.', imageUrl: T[1], tags: ['manga', 'figures', 'vintage', 'otaku', 'cosplay'] },
  { id: 'o51', name: 'Osaka Gundambar', kanji: '大阪ガンダムバー', category: 'Anime', area: 'Osaka', priority: 3, coordinates: { lat: 34.6690, lng: 135.5000 }, shortDescription: 'Themed bar surrounded by Gundam model kits and anime memorabilia.', imageUrl: T[1], tags: ['gundam', 'bar', 'mecha', 'otaku'] },
  { id: 'o52', name: 'Universal Studios Japan', kanji: 'ユニバーサル・スタジオ・ジャパン', category: 'Anime', area: 'Osaka', priority: 1, coordinates: { lat: 34.6656, lng: 135.4323 }, shortDescription: 'Theme park with Nintendo World, anime attractions and rides.', imageUrl: T[1], tags: ['nintendo', 'theme-park', 'anime-events', 'entertainment'] },
  { id: 'o53', name: 'Nipponbashi Street Festa Venue', kanji: '日本橋ストリートフェスタ会場', category: 'Anime', area: 'Osaka', priority: 2, coordinates: { lat: 34.6595, lng: 135.5055 }, shortDescription: 'Annual massive cosplay parade and otaku festival street.', imageUrl: T[1], tags: ['cosplay', 'festival', 'otaku', 'event'] },

  // --- Osaka: Shopping ---
  { id: 'o54', name: 'Shinsaibashi-suji', kanji: '心斎橋筋商店街', category: 'Shopping', area: 'Osaka', priority: 1, coordinates: { lat: 34.6729, lng: 135.5012 }, shortDescription: 'Osaka\'s premier covered shopping arcade from Shinsaibashi to Namba.', imageUrl: T[3], tags: ['arcade', 'fashion', 'department-store', 'souvenir'] },
  { id: 'o55', name: 'Umeda (Grand Front & HEP Five)', kanji: '梅田エリア', category: 'Shopping', area: 'Osaka', priority: 1, coordinates: { lat: 34.7050, lng: 135.4967 }, shortDescription: 'Massive shopping district with malls, department stores and Ferris wheel.', imageUrl: T[3], tags: ['department-store', 'fashion', 'modern', 'entertainment'] },
  { id: 'o56', name: 'Amerikamura', kanji: 'アメリカ村', category: 'Shopping', area: 'Osaka', priority: 1, coordinates: { lat: 34.6720, lng: 135.4980 }, shortDescription: 'Youth fashion district with vintage shops and street art.', imageUrl: T[3], tags: ['vintage', 'streetwear', 'youth', 'art'] },
  { id: 'o57', name: 'Tenmabashi Antique Area', kanji: '天満橋アンティーク', category: 'Shopping', area: 'Osaka', priority: 3, coordinates: { lat: 34.6912, lng: 135.5175 }, shortDescription: 'Cluster of antique shops near Osaka Castle with Japanese treasures.', imageUrl: T[3], tags: ['antique', 'vintage', 'ceramics', 'traditional'] },
  { id: 'o58', name: 'Namba Walk Underground Mall', kanji: 'なんばウォーク', category: 'Shopping', area: 'Osaka', priority: 2, coordinates: { lat: 34.6655, lng: 135.5013 }, shortDescription: 'Extensive underground shopping mall connecting major stations.', imageUrl: T[3], tags: ['underground', 'fashion', 'convenience', 'modern'] },
  { id: 'o59', name: 'Sakai Knife Shops Street', kanji: '堺打刃物通り', category: 'Shopping', area: 'Osaka', priority: 2, coordinates: { lat: 34.5730, lng: 135.4835 }, shortDescription: 'Street lined with world-class Japanese kitchen knife shops.', imageUrl: T[3], tags: ['knife', 'kitchen', 'artisan', 'souvenir'] },

  // =============================================
  // NARA (n1–n100)
  // =============================================

  // --- Nara: Culture ---
  { id: 'n1', name: 'Todai-ji', kanji: '東大寺', category: 'Culture', area: 'Nara', priority: 1, coordinates: { lat: 34.6889, lng: 135.8398 }, shortDescription: 'Home to Japan\'s largest bronze Buddha statue.', imageUrl: T[2], tags: ['temple', 'buddha', 'unesco', 'national-treasure'] },
  { id: 'n2', name: 'Kofuku-ji', kanji: '興福寺', category: 'Culture', area: 'Nara', priority: 1, coordinates: { lat: 34.6831, lng: 135.8310 }, shortDescription: 'Historic temple complex with stunning five-story pagoda.', imageUrl: T[1], tags: ['temple', 'pagoda', 'museum', 'fujiwara'] },
  { id: 'n3', name: 'Kasuga Taisha', kanji: '春日大社', category: 'Culture', area: 'Nara', priority: 1, coordinates: { lat: 34.6814, lng: 135.8483 }, shortDescription: 'Forest shrine with thousands of stone and bronze lanterns.', imageUrl: T[5], tags: ['shrine', 'lanterns', 'forest', 'festival'] },
  { id: 'n7', name: 'Yakushi-ji', kanji: '薬師寺', category: 'Culture', area: 'Nara', priority: 1, coordinates: { lat: 34.6683, lng: 135.7843 }, shortDescription: 'UNESCO temple with East Pagoda, Japan\'s frozen music.', imageUrl: T[2], tags: ['temple', 'unesco', 'pagoda', 'healing'] },
  { id: 'n8', name: 'Toshodai-ji', kanji: '唐招提寺', category: 'Culture', area: 'Nara', priority: 1, coordinates: { lat: 34.6753, lng: 135.7857 }, shortDescription: 'Temple founded by Chinese monk Ganjin in 759 AD.', imageUrl: T[2], tags: ['temple', 'unesco', 'chinese', 'nara-period'] },
  { id: 'n9', name: 'Horyu-ji', kanji: '法隆寺', category: 'Culture', area: 'Nara', priority: 1, coordinates: { lat: 34.6147, lng: 135.7353 }, shortDescription: 'World\'s oldest wooden buildings, Japan\'s first UNESCO site.', imageUrl: T[2], tags: ['temple', 'unesco', 'ancient', 'shotoku'] },
  { id: 'n10', name: 'Hase-dera', kanji: '長谷寺', category: 'Culture', area: 'Nara', priority: 2, coordinates: { lat: 34.5354, lng: 135.9014 }, shortDescription: 'Temple of flowers with covered stairway of 399 steps.', imageUrl: T[2], tags: ['temple', 'flowers', 'peony', 'pilgrimage'] },
  { id: 'n11', name: 'Taimadera', kanji: '當麻寺', category: 'Culture', area: 'Nara', priority: 3, coordinates: { lat: 34.5178, lng: 135.6968 }, shortDescription: 'Ancient temple with twin pagodas and mandala legend.', imageUrl: T[2], tags: ['temple', 'pagoda', 'mandala', 'ancient'] },
  { id: 'n12', name: 'Muro-ji', kanji: '室生寺', category: 'Culture', area: 'Nara', priority: 3, coordinates: { lat: 34.5379, lng: 136.0376 }, shortDescription: 'Mountain temple open to women when others were not, smallest five-story pagoda.', imageUrl: T[2], tags: ['temple', 'mountain', 'pagoda', 'women'] },
  { id: 'n13', name: 'Tanzan Shrine', kanji: '談山神社', category: 'Culture', area: 'Nara', priority: 2, coordinates: { lat: 34.4614, lng: 135.8595 }, shortDescription: 'Mountain shrine with 13-story pagoda, spectacular autumn colors.', imageUrl: T[5], tags: ['shrine', 'pagoda', 'autumn-leaves', 'mountain'] },

  // --- Nara: Zen ---
  { id: 'n5', name: 'Isuien Garden', kanji: '依水園', category: 'Zen', area: 'Nara', priority: 2, coordinates: { lat: 34.6870, lng: 135.8363 }, shortDescription: 'Exquisite traditional garden with views of Todai-ji.', imageUrl: T[0], tags: ['garden', 'borrowed-scenery', 'tea', 'meditation'] },
  { id: 'n14', name: 'Yoshiki-en Garden', kanji: '吉城園', category: 'Zen', area: 'Nara', priority: 3, coordinates: { lat: 34.6871, lng: 135.8352 }, shortDescription: 'Free traditional garden with moss garden next to Isuien.', imageUrl: T[6], tags: ['garden', 'moss', 'free', 'meditation'] },
  { id: 'n15', name: 'Gangō-ji Zen Garden', kanji: '元興寺庭園', category: 'Zen', area: 'Nara', priority: 2, coordinates: { lat: 34.6780, lng: 135.8328 }, shortDescription: 'UNESCO temple with serene stone garden and ancient roof tiles.', imageUrl: T[6], tags: ['zen', 'garden', 'unesco', 'ancient'] },
  { id: 'n16', name: 'Isui-en Sanshu-tei Teahouse', kanji: '依水園三秀亭', category: 'Zen', area: 'Nara', priority: 3, coordinates: { lat: 34.6870, lng: 135.8360 }, shortDescription: 'Traditional teahouse within Isuien with garden contemplation.', imageUrl: T[6], tags: ['tea', 'tea-ceremony', 'meditation', 'garden'] },
  { id: 'n17', name: 'Shin-Yakushi-ji', kanji: '新薬師寺', category: 'Zen', area: 'Nara', priority: 2, coordinates: { lat: 34.6752, lng: 135.8465 }, shortDescription: 'Intimate temple with twelve divine generals, a quiet meditation spot.', imageUrl: T[6], tags: ['temple', 'sculpture', 'meditation', 'quiet'] },
  { id: 'n18', name: 'Joruri-ji', kanji: '浄瑠璃寺', category: 'Zen', area: 'Nara', priority: 3, coordinates: { lat: 34.7169, lng: 135.8934 }, shortDescription: 'Paradise garden temple with nine Amida Buddhas in a row.', imageUrl: T[6], tags: ['garden', 'paradise', 'buddha', 'meditation'] },

  // --- Nara: Samurai ---
  { id: 'n19', name: 'Yamato Koriyama Castle', kanji: '大和郡山城', category: 'Samurai', area: 'Nara', priority: 2, coordinates: { lat: 34.6490, lng: 135.7824 }, shortDescription: 'Castle ruins with cherry blossoms and goldfish town.', imageUrl: T[2], tags: ['castle', 'cherry-blossom', 'history', 'goldfish'] },
  { id: 'n20', name: 'Takatori Castle Ruins', kanji: '高取城跡', category: 'Samurai', area: 'Nara', priority: 3, coordinates: { lat: 34.4410, lng: 135.7784 }, shortDescription: 'One of Japan\'s highest mountain castles with dramatic stone walls.', imageUrl: T[2], tags: ['castle', 'mountain', 'ruins', 'hiking'] },
  { id: 'n21', name: 'Yoshino Mountain', kanji: '吉野山', category: 'Samurai', area: 'Nara', priority: 2, coordinates: { lat: 34.3692, lng: 135.8586 }, shortDescription: 'Mountain stronghold of Emperor Go-Daigo and 30,000 cherry trees.', imageUrl: T[2], tags: ['mountain', 'cherry-blossom', 'emperor', 'history'] },
  { id: 'n22', name: 'Kasagi Castle Ruins', kanji: '笠置城跡', category: 'Samurai', area: 'Nara', priority: 3, coordinates: { lat: 34.7557, lng: 135.9405 }, shortDescription: 'Ruins where Emperor Go-Daigo staged his rebellion.', imageUrl: T[2], tags: ['castle', 'ruins', 'emperor', 'history'] },
  { id: 'n23', name: 'Uda-Matsuyama Castle Town', kanji: '宇陀松山城下町', category: 'Samurai', area: 'Nara', priority: 3, coordinates: { lat: 34.4899, lng: 135.9492 }, shortDescription: 'Preserved Edo-era castle town with merchant houses.', imageUrl: T[2], tags: ['castle-town', 'edo', 'preserved', 'machiya'] },

  // --- Nara: Nature ---
  { id: 'n4', name: 'Nara Park', kanji: '奈良公園', category: 'Nature', area: 'Nara', priority: 1, coordinates: { lat: 34.6851, lng: 135.8377 }, shortDescription: 'Vast park where friendly deer roam freely.', imageUrl: T[0], tags: ['deer', 'park', 'cherry-blossom', 'autumn-leaves'] },
  { id: 'n24', name: 'Mount Wakakusa', kanji: '若草山', category: 'Nature', area: 'Nara', priority: 1, coordinates: { lat: 34.6883, lng: 135.8490 }, shortDescription: 'Grassy hillside with panoramic views of Nara, famous for grass burning festival.', imageUrl: T[4], tags: ['mountain', 'panorama', 'festival', 'fire'] },
  { id: 'n25', name: 'Kasugayama Primeval Forest', kanji: '春日山原始林', category: 'Nature', area: 'Nara', priority: 2, coordinates: { lat: 34.6808, lng: 135.8555 }, shortDescription: 'UNESCO-listed primeval forest untouched for over 1000 years.', imageUrl: T[4], tags: ['forest', 'ancient', 'unesco', 'hiking'] },
  { id: 'n26', name: 'Yoshino Cherry Blossom Mountain', kanji: '吉野山桜', category: 'Nature', area: 'Nara', priority: 1, coordinates: { lat: 34.3692, lng: 135.8586 }, shortDescription: 'Japan\'s most famous cherry blossom site with 30,000 trees.', imageUrl: T[4], tags: ['cherry-blossom', 'mountain', 'unesco', 'hanami'] },
  { id: 'n27', name: 'Mitarai Valley', kanji: 'みたらい渓谷', category: 'Nature', area: 'Nara', priority: 3, coordinates: { lat: 34.2775, lng: 135.8360 }, shortDescription: 'Crystal clear gorge with emerald pools and autumn foliage.', imageUrl: T[4], tags: ['gorge', 'river', 'autumn-leaves', 'hiking'] },
  { id: 'n28', name: 'Nara Deer Senbei Area', kanji: '鹿せんべい売場', category: 'Nature', area: 'Nara', priority: 1, coordinates: { lat: 34.6850, lng: 135.8370 }, shortDescription: 'Central spot to interact with Nara\'s sacred deer.', imageUrl: T[0], tags: ['deer', 'interaction', 'family', 'photo-spot'] },
  { id: 'n29', name: 'Soni Highland', kanji: '曽爾高原', category: 'Nature', area: 'Nara', priority: 3, coordinates: { lat: 34.5203, lng: 136.1580 }, shortDescription: 'Golden pampas grass plateau with stunning sunset views.', imageUrl: T[4], tags: ['pampas', 'sunset', 'highland', 'autumn'] },

  // --- Nara: DailyLife ---
  { id: 'n6', name: 'Naramachi', kanji: 'ならまち', category: 'DailyLife', area: 'Nara', priority: 2, coordinates: { lat: 34.6780, lng: 135.8310 }, shortDescription: 'Historic merchant quarter with machiya townhouses.', imageUrl: T[3], tags: ['machiya', 'neighborhood', 'local', 'traditional'] },
  { id: 'n30', name: 'Higashimuki Shopping Street', kanji: '東向商店街', category: 'DailyLife', area: 'Nara', priority: 2, coordinates: { lat: 34.6818, lng: 135.8280 }, shortDescription: 'Nara\'s main covered shopping arcade near JR station.', imageUrl: T[3], tags: ['shotengai', 'local', 'shopping', 'market'] },
  { id: 'n31', name: 'Nara Hotel', kanji: '奈良ホテル', category: 'DailyLife', area: 'Nara', priority: 3, coordinates: { lat: 34.6815, lng: 135.8339 }, shortDescription: 'Grand heritage hotel from 1909 with classical architecture.', imageUrl: T[2], tags: ['architecture', 'meiji', 'heritage', 'hotel'] },
  { id: 'n32', name: 'Sarusawa Pond', kanji: '猿沢池', category: 'DailyLife', area: 'Nara', priority: 2, coordinates: { lat: 34.6817, lng: 135.8305 }, shortDescription: 'Scenic pond reflecting the five-story pagoda, a classic Nara scene.', imageUrl: T[0], tags: ['pond', 'reflection', 'photo-spot', 'relaxation'] },
  { id: 'n33', name: 'Kintetsu Nara Station Area', kanji: '近鉄奈良駅前', category: 'DailyLife', area: 'Nara', priority: 2, coordinates: { lat: 34.6822, lng: 135.8283 }, shortDescription: 'Bustling area with shops, cafes and gateway to Nara Park.', imageUrl: T[3], tags: ['station', 'hub', 'local', 'cafe'] },
  { id: 'n34', name: 'Takabatake Area', kanji: '高畑エリア', category: 'DailyLife', area: 'Nara', priority: 3, coordinates: { lat: 34.6750, lng: 135.8420 }, shortDescription: 'Quiet residential area loved by literary figures, with hidden cafes.', imageUrl: T[3], tags: ['neighborhood', 'quiet', 'literary', 'cafe'] },

  // --- Nara: Food ---
  { id: 'n35', name: 'Nakatanidou Mochi', kanji: '中谷堂', category: 'Food', area: 'Nara', priority: 1, coordinates: { lat: 34.6818, lng: 135.8290 }, shortDescription: 'Famous mochi pounding performance shop on the main street.', imageUrl: T[3], tags: ['mochi', 'performance', 'street-food', 'traditional'] },
  { id: 'n36', name: 'Kura Sushi Nara', kanji: 'くら寿司奈良店', category: 'Food', area: 'Nara', priority: 3, coordinates: { lat: 34.6810, lng: 135.8260 }, shortDescription: 'Fun conveyor belt sushi with gacha game reward system.', imageUrl: T[3], tags: ['sushi', 'conveyor-belt', 'family', 'affordable'] },
  { id: 'n37', name: 'Tsukihi-tei', kanji: '月日亭', category: 'Food', area: 'Nara', priority: 2, coordinates: { lat: 34.6840, lng: 135.8400 }, shortDescription: 'Traditional kaiseki restaurant inside Nara Park.', imageUrl: T[3], tags: ['kaiseki', 'traditional', 'park', 'fine-dining'] },
  { id: 'n38', name: 'Menme Ramen', kanji: '麺闘庵', category: 'Food', area: 'Nara', priority: 3, coordinates: { lat: 34.6785, lng: 135.8300 }, shortDescription: 'Local ramen shop famous for udon served in a tofu pouch.', imageUrl: T[3], tags: ['ramen', 'udon', 'tofu', 'unique'] },
  { id: 'n39', name: 'Kakinoha Sushi Tanaka', kanji: '柿の葉寿司たなか', category: 'Food', area: 'Nara', priority: 2, coordinates: { lat: 34.6825, lng: 135.8278 }, shortDescription: 'Nara\'s signature persimmon leaf-wrapped pressed sushi.', imageUrl: T[3], tags: ['sushi', 'persimmon', 'traditional', 'souvenir'] },
  { id: 'n40', name: 'Harushika Sake Brewery', kanji: '春鹿醸造', category: 'Food', area: 'Nara', priority: 2, coordinates: { lat: 34.6780, lng: 135.8300 }, shortDescription: 'Historic sake brewery in Naramachi offering tastings.', imageUrl: T[3], tags: ['sake', 'brewery', 'tasting', 'naramachi'] },
  { id: 'n41', name: 'Sanjo Street Dining', kanji: '三条通り飲食街', category: 'Food', area: 'Nara', priority: 2, coordinates: { lat: 34.6805, lng: 135.8260 }, shortDescription: 'Main street connecting the station to Nara Park lined with restaurants.', imageUrl: T[3], tags: ['dining', 'variety', 'street', 'local'] },

  // --- Nara: Craft ---
  { id: 'n42', name: 'Nara Sumi Ink Making', kanji: '奈良墨作り', category: 'Craft', area: 'Nara', priority: 2, coordinates: { lat: 34.6790, lng: 135.8290 }, shortDescription: 'Traditional sumi ink production center, Nara makes 95% of Japan\'s ink.', imageUrl: T[3], tags: ['calligraphy', 'ink', 'traditional', 'workshop'] },
  { id: 'n43', name: 'Nara Brush Workshop', kanji: '奈良筆体験', category: 'Craft', area: 'Nara', priority: 3, coordinates: { lat: 34.6800, lng: 135.8300 }, shortDescription: 'Hands-on experience making traditional calligraphy brushes.', imageUrl: T[3], tags: ['calligraphy', 'brush', 'workshop', 'traditional'] },
  { id: 'n44', name: 'Naramachi Mechanical Toy Museum', kanji: 'ならまちからくりおもちゃ館', category: 'Craft', area: 'Nara', priority: 3, coordinates: { lat: 34.6768, lng: 135.8315 }, shortDescription: 'Free museum of traditional wooden karakuri toys you can play with.', imageUrl: T[3], tags: ['woodwork', 'toy', 'museum', 'traditional', 'free'] },
  { id: 'n45', name: 'Akahada Pottery Kiln', kanji: '赤膚焼窯元', category: 'Craft', area: 'Nara', priority: 3, coordinates: { lat: 34.6660, lng: 135.7750 }, shortDescription: 'Traditional Nara pottery kiln producing Akahada-yaki since the Edo period.', imageUrl: T[3], tags: ['pottery', 'ceramics', 'workshop', 'edo'] },
  { id: 'n46', name: 'Nara Sarashi Textile', kanji: '奈良晒', category: 'Craft', area: 'Nara', priority: 3, coordinates: { lat: 34.6780, lng: 135.8280 }, shortDescription: 'Traditional Nara-bleached linen textile shops in Naramachi.', imageUrl: T[3], tags: ['textile', 'linen', 'traditional', 'naramachi'] },

  // --- Nara: Anime ---
  { id: 'n47', name: 'Nara Anime Event Space', kanji: '奈良アニメイベント', category: 'Anime', area: 'Nara', priority: 3, coordinates: { lat: 34.6840, lng: 135.8270 }, shortDescription: 'Venue for seasonal anime and manga events near Nara Park.', imageUrl: T[1], tags: ['anime-events', 'manga', 'seasonal', 'cosplay'] },
  { id: 'n48', name: 'Deer & Anime Photo Spots', kanji: '鹿アニメスポット', category: 'Anime', area: 'Nara', priority: 3, coordinates: { lat: 34.6855, lng: 135.8380 }, shortDescription: 'Popular spots where anime fans photograph deer in cosplay settings.', imageUrl: T[1], tags: ['deer', 'photo-spot', 'cosplay', 'unique'] },
  { id: 'n49', name: 'Book Off Nara', kanji: 'ブックオフ奈良', category: 'Anime', area: 'Nara', priority: 3, coordinates: { lat: 34.6810, lng: 135.8230 }, shortDescription: 'Second-hand bookstore with extensive manga and anime goods section.', imageUrl: T[1], tags: ['manga', 'shopping', 'vintage', 'books'] },
  { id: 'n50', name: 'Asuka Village (Ancient Anime Roots)', kanji: '飛鳥', category: 'Anime', area: 'Nara', priority: 3, coordinates: { lat: 34.4746, lng: 135.8202 }, shortDescription: 'Ancient village featured in historical anime and manga set in ancient Japan.', imageUrl: T[1], tags: ['history', 'ancient', 'pilgrimage', 'manga-location'] },

  // --- Nara: Shopping ---
  { id: 'n51', name: 'Nara Souvenir Street', kanji: '奈良みやげ通り', category: 'Shopping', area: 'Nara', priority: 2, coordinates: { lat: 34.6830, lng: 135.8295 }, shortDescription: 'Shopping street near Kofukuji with Nara\'s best souvenirs.', imageUrl: T[3], tags: ['souvenir', 'deer-goods', 'traditional', 'gifts'] },
  { id: 'n52', name: 'Naramachi Lattice House Shops', kanji: 'ならまち格子の家', category: 'Shopping', area: 'Nara', priority: 2, coordinates: { lat: 34.6770, lng: 135.8315 }, shortDescription: 'Restored machiya houses converted into craft and gift shops.', imageUrl: T[3], tags: ['machiya', 'crafts', 'artisan', 'local-brand'] },
  { id: 'n53', name: 'Mochiidono Center Street', kanji: 'もちいどのセンター街', category: 'Shopping', area: 'Nara', priority: 2, coordinates: { lat: 34.6810, lng: 135.8290 }, shortDescription: 'Charming covered arcade with local shops and cafes.', imageUrl: T[3], tags: ['arcade', 'local', 'shopping', 'cafe'] },
  { id: 'n54', name: 'Yu Nakagawa Hemp Goods', kanji: '遊 中川', category: 'Shopping', area: 'Nara', priority: 3, coordinates: { lat: 34.6775, lng: 135.8310 }, shortDescription: 'Modern Nara brand selling hemp and linen goods with traditional roots.', imageUrl: T[3], tags: ['local-brand', 'linen', 'modern', 'design'] },
  { id: 'n55', name: 'Nara Shikadeer Cookie Shop', kanji: '奈良鹿クッキー', category: 'Shopping', area: 'Nara', priority: 3, coordinates: { lat: 34.6820, lng: 135.8280 }, shortDescription: 'Cute deer-shaped cookies and sweets unique to Nara.', imageUrl: T[3], tags: ['souvenir', 'sweets', 'deer', 'cute'] },

  // --- Nara: Zen (additional) ---
  { id: 'n56', name: 'Enjō-ji Temple', kanji: '円成寺', category: 'Zen', area: 'Nara', priority: 3, coordinates: { lat: 34.7038, lng: 135.8893 }, shortDescription: 'Mountain temple with beautiful Pure Land garden and Unkei sculpture.', imageUrl: T[6], tags: ['garden', 'sculpture', 'mountain', 'meditation'] },

  // Additional Kyoto spots to reach ~100
  { id: 'k79', name: 'Daikaku-ji', kanji: '大覚寺', category: 'Culture', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0257, lng: 135.6683 }, shortDescription: 'Imperial temple on Osawa Pond, Arashiyama\'s hidden gem.', imageUrl: T[2], tags: ['temple', 'pond', 'imperial', 'arashiyama'] },
  { id: 'k80', name: 'Monkey Park Iwatayama', kanji: '嵐山モンキーパーク', category: 'Nature', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0097, lng: 135.6759 }, shortDescription: 'Mountain park with wild monkeys and panoramic city views.', imageUrl: T[4], tags: ['monkey', 'mountain', 'panorama', 'arashiyama'] },
  { id: 'k81', name: 'Kyoto Tower', kanji: '京都タワー', category: 'DailyLife', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9874, lng: 135.7590 }, shortDescription: 'Iconic tower opposite Kyoto Station with observation deck.', imageUrl: T[2], tags: ['tower', 'observation', 'landmark', 'night-view'] },
  { id: 'k82', name: 'Sanjo Ohashi Bridge', kanji: '三条大橋', category: 'DailyLife', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0089, lng: 135.7715 }, shortDescription: 'Historic bridge that was the terminus of the Tokaido road.', imageUrl: T[3], tags: ['bridge', 'history', 'tokaido', 'river'] },
  { id: 'k83', name: 'Uji Byodo-in', kanji: '平等院', category: 'Culture', area: 'Kyoto', priority: 1, coordinates: { lat: 34.8893, lng: 135.8076 }, shortDescription: 'Phoenix Hall depicted on the 10-yen coin, a Pure Land masterpiece.', imageUrl: T[2], tags: ['temple', 'unesco', 'phoenix', 'uji', 'national-treasure'] },
  { id: 'k84', name: 'Uji Matcha Street', kanji: '宇治抹茶通り', category: 'Food', area: 'Kyoto', priority: 2, coordinates: { lat: 34.8890, lng: 135.8050 }, shortDescription: 'Historic street lined with matcha tea shops in the heart of Uji.', imageUrl: T[3], tags: ['matcha', 'uji', 'tea', 'sweets', 'traditional'] },
  { id: 'k85', name: 'Zuiho-in', kanji: '瑞峯院', category: 'Zen', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0442, lng: 135.7455 }, shortDescription: 'Sub-temple of Daitoku-ji with hidden cross-shaped rock garden.', imageUrl: T[6], tags: ['rock-garden', 'hidden', 'meditation', 'zen'] },
  { id: 'k86', name: 'Okochi Sanso Villa', kanji: '大河内山荘', category: 'Nature', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0183, lng: 135.6697 }, shortDescription: 'Film actor\'s villa with exquisite gardens and mountain views.', imageUrl: T[4], tags: ['garden', 'villa', 'arashiyama', 'tea'] },
  { id: 'k87', name: 'Kimono Forest', kanji: 'キモノフォレスト', category: 'Craft', area: 'Kyoto', priority: 2, coordinates: { lat: 35.0120, lng: 135.6780 }, shortDescription: 'Installation of 600 illuminated kimono fabric pillars at Randen station.', imageUrl: T[3], tags: ['kimono', 'textile', 'art', 'illumination'] },
  { id: 'k88', name: 'Gekkeikan Okura Sake Museum', kanji: '月桂冠大倉記念館', category: 'Food', area: 'Kyoto', priority: 2, coordinates: { lat: 34.9310, lng: 135.7590 }, shortDescription: 'Historic sake museum in Fushimi with tastings included.', imageUrl: T[3], tags: ['sake', 'museum', 'tasting', 'fushimi'] },
  { id: 'k89', name: 'Otagi Nenbutsu-ji', kanji: '愛宕念仏寺', category: 'Culture', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0243, lng: 135.6546 }, shortDescription: 'Remote temple with 1200 whimsical stone rakan statues.', imageUrl: T[2], tags: ['temple', 'sculpture', 'unique', 'hidden-gem'] },
  { id: 'k90', name: 'Gio-ji', kanji: '祇王寺', category: 'Zen', area: 'Kyoto', priority: 3, coordinates: { lat: 35.0215, lng: 135.6628 }, shortDescription: 'Tiny moss-covered temple with tragic love story in Arashiyama.', imageUrl: T[6], tags: ['moss', 'garden', 'quiet', 'arashiyama'] },

  // Additional Osaka spots
  { id: 'o60', name: 'Abeno Harukas', kanji: 'あべのハルカス', category: 'DailyLife', area: 'Osaka', priority: 1, coordinates: { lat: 34.6463, lng: 135.5136 }, shortDescription: 'Japan\'s tallest skyscraper with 360-degree observation deck.', imageUrl: T[2], tags: ['observation', 'skyscraper', 'modern', 'night-view'] },
  { id: 'o61', name: 'Osaka Aquarium Kaiyukan', kanji: '海遊館', category: 'Nature', area: 'Osaka', priority: 1, coordinates: { lat: 34.6545, lng: 135.4289 }, shortDescription: 'One of the world\'s largest aquariums with whale shark tank.', imageUrl: T[4], tags: ['aquarium', 'whale-shark', 'family', 'marine'] },
  { id: 'o62', name: 'Tempozan Ferris Wheel', kanji: '天保山大観覧車', category: 'DailyLife', area: 'Osaka', priority: 2, coordinates: { lat: 34.6542, lng: 135.4316 }, shortDescription: 'Giant Ferris wheel with transparent gondolas next to the harbor.', imageUrl: T[2], tags: ['ferris-wheel', 'harbor', 'night-view', 'entertainment'] },
  { id: 'o63', name: 'Namba Grand Kagutsu Comedy', kanji: 'なんば花月', category: 'DailyLife', area: 'Osaka', priority: 2, coordinates: { lat: 34.6676, lng: 135.5040 }, shortDescription: 'Osaka\'s comedy theater - experience manzai humor culture.', imageUrl: T[3], tags: ['comedy', 'manzai', 'entertainment', 'culture'] },
  { id: 'o64', name: 'Momofuku Ando Instant Ramen Museum', kanji: 'インスタントラーメン発明記念館', category: 'Food', area: 'Osaka', priority: 2, coordinates: { lat: 34.8268, lng: 135.4326 }, shortDescription: 'Birthplace of instant ramen in Ikeda, make your own Chicken Ramen.', imageUrl: T[3], tags: ['ramen', 'museum', 'experience', 'invention'] },
  { id: 'o65', name: 'Hozen-ji Yokocho Bars', kanji: '法善寺横丁バー', category: 'Food', area: 'Osaka', priority: 3, coordinates: { lat: 34.6684, lng: 135.5032 }, shortDescription: 'Hidden cocktail bars in the atmospheric alley behind Hozenji.', imageUrl: T[3], tags: ['bar', 'cocktail', 'nightlife', 'hidden-gem'] },
  { id: 'o66', name: 'Hagimairi Road (Sumiyoshi)', kanji: '萩参道', category: 'DailyLife', area: 'Osaka', priority: 3, coordinates: { lat: 34.6127, lng: 135.4940 }, shortDescription: 'Traditional approach road to Sumiyoshi Taisha with local atmosphere.', imageUrl: T[3], tags: ['local', 'traditional', 'walk', 'neighborhood'] },
  { id: 'o67', name: 'Osaka Shochikuza Theatre', kanji: '大阪松竹座', category: 'Culture', area: 'Osaka', priority: 2, coordinates: { lat: 34.6690, lng: 135.5030 }, shortDescription: 'Historic theater for kabuki and traditional performing arts.', imageUrl: T[2], tags: ['kabuki', 'theater', 'traditional', 'performance'] },
  { id: 'o68', name: 'Nakanoshima Museum of Art', kanji: '大阪中之島美術館', category: 'Culture', area: 'Osaka', priority: 2, coordinates: { lat: 34.6925, lng: 135.4890 }, shortDescription: 'Striking black cube museum of modern and contemporary art.', imageUrl: T[2], tags: ['museum', 'art', 'modern', 'architecture'] },

  // Additional Nara spots
  { id: 'n57', name: 'Nara National Museum', kanji: '奈良国立博物館', category: 'Culture', area: 'Nara', priority: 1, coordinates: { lat: 34.6845, lng: 135.8382 }, shortDescription: 'Premier Buddhist art museum adjacent to Nara Park.', imageUrl: T[2], tags: ['museum', 'buddhism', 'art', 'national-treasure'] },
  { id: 'n58', name: 'Ishibutai Kofun', kanji: '石舞台古墳', category: 'Culture', area: 'Nara', priority: 2, coordinates: { lat: 34.4669, lng: 135.8234 }, shortDescription: 'Japan\'s largest exposed megalithic tomb from the 6th century.', imageUrl: T[2], tags: ['ancient', 'tomb', 'megalith', 'asuka'] },
  { id: 'n59', name: 'Asuka Historical Museum', kanji: '飛鳥資料館', category: 'Culture', area: 'Nara', priority: 3, coordinates: { lat: 34.4720, lng: 135.8165 }, shortDescription: 'Museum covering the Asuka Period when Nara was Japan\'s capital.', imageUrl: T[2], tags: ['museum', 'ancient', 'asuka', 'history'] },
  { id: 'n60', name: 'Heijo Palace Ruins', kanji: '平城宮跡', category: 'Culture', area: 'Nara', priority: 1, coordinates: { lat: 34.6949, lng: 135.8019 }, shortDescription: 'Reconstructed Nara Period imperial palace, UNESCO World Heritage.', imageUrl: T[2], tags: ['palace', 'unesco', 'nara-period', 'reconstruction'] },
  { id: 'n61', name: 'Taima-no-Kechimyaku Trail', kanji: '當麻の道', category: 'Nature', area: 'Nara', priority: 3, coordinates: { lat: 34.5200, lng: 135.7000 }, shortDescription: 'Countryside walk through fields with views of Mount Nijo.', imageUrl: T[4], tags: ['countryside', 'walk', 'mountain', 'rural'] },
  { id: 'n62', name: 'Koriyama Goldfish Town', kanji: '大和郡山金魚の町', category: 'DailyLife', area: 'Nara', priority: 3, coordinates: { lat: 34.6500, lng: 135.7830 }, shortDescription: 'Town famous for goldfish breeding with fish-themed manhole covers.', imageUrl: T[3], tags: ['goldfish', 'local', 'unique', 'town'] },
  { id: 'n63', name: 'Omiwa Shrine', kanji: '大神神社', category: 'Culture', area: 'Nara', priority: 2, coordinates: { lat: 34.5275, lng: 135.8528 }, shortDescription: 'Japan\'s oldest shrine with no main hall — the mountain itself is the deity.', imageUrl: T[5], tags: ['shrine', 'ancient', 'mountain', 'spiritual', 'sake'] },
];
